[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Cython",
    "pybind11~=2.6.0",
    "scikit-build",
    "cmake",
    "ninja; sys_platform != 'Windows'"
]
build-backend = "setuptools.build_meta"
