name: wheels

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_wheels:
    name: Build ALE Python on ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        config: [
          {"os": "ubuntu-20.04", "deps": ["re2"], "triplet": "x64-linux"},
          {"os": "windows-latest", "deps": ["re2"], "triplet": "x64-windows"},
          {"os": "macos-latest", "deps": ["re2"], "triplet": "x64-osx"}
        ]
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Cancel previous runs on the same branch
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Docker Login
        if: matrix.config.os == 'ubuntu-latest'
        run: docker login ghcr.io --username "${GITHUB_ACTOR}" --password "${GITHUB_CR_TOKEN}"
        env:
          GITHUB_CR_TOKEN: ${{ secrets.CR_TOKEN }}

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-cibw.txt

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: "ghcr.io/mgbellemare/manylinux2014-vcpkg"
          CIBW_BUILD: "cp3[6789]-*"
          CIBW_SKIP: "*i686* *win32*"
          CIBW_ENVIRONMENT: "VCPKG_DEFAULT_TRIPLET=${{ matrix.config.triplet }}"
          CIBW_BEFORE_ALL: "vcpkg install ${{ join(matrix.config.deps, ' ') }} --triplet ${{ matrix.config.triplet }}"

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  check_artifacts:
    name: Check artifacts are correct
    needs: [build_wheels]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: wheels
          
      - name: Check number of downloaded artifacts
        #run: .github/workflows/wheel-check.sh 9
        run: ls -l ./wheelhouse/*.whl
