name: wheels

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} for Python
    runs-on: ${{ matrix.os }}
    env:
      MANYLINUX2010_X86_64_TAG: "2020-12-03-912b0de"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.7

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.7.1
      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y
      - name: Build wheels
        env:
          CIBW_BEFORE_ALL_LINUX: >
            yum -y -q --enablerepo=extras install epel-release
            && yum install -y re2-devel
          CIBW_BEFORE_ALL_MACOS: brew install re2
          CIBW_BUILD: cp36-* cp37-* cp38-*
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Build sdist
        run: |
          pip install --user cython
          python setup.py sdist

  check_artifacts:
    name: Check artifacts are correct
    needs: [build_wheels]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: wheels
          
      - name: Check number of downloaded artifacts
        run: .github/workflows/wheel-check.sh 9
