name: Release

on:
  push:
    # release on tag push
    tags:
      - '*'

jobs:
  create_wheels:
    name: Build wheels on ${{ matrix.os }} for Python
    runs-on: ${{ matrix.os }}
    env:
      MANYLINUX2010_X86_64_TAG: "2020-12-03-912b0de"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.7

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.7.1
      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y
      - name: Build wheels
        env:
          CIBW_BEFORE_ALL_LINUX: >
            yum -y -q --enablerepo=extras install epel-release
            && yum install -y re2-devel
          CIBW_BEFORE_ALL_MACOS: brew install re2
          CIBW_BUILD: cp36-* cp37-* cp38-*
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  create_release:
    name: Create Release
    needs: [create_wheels]
    runs-on: ubuntu-20.04

    steps:
      - name: Get version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo ${{ env.VERSION }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.7

      - uses: actions/download-artifact@v2
        with:
          name: wheels

      - name: Install gitchangelog
        run: |
          pip install git+https://github.com/freepn/gitchangelog@3.0.4-4

      - name: Generate changes file
        run: |
          bash -c 'gitchangelog $(git tag --sort=taggerdate | tail -n2 | head -n1)..${{ env.VERSION }} > CHANGES.md'

      - name: Create draft release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body_path: CHANGES.md
          draft: false
          prerelease: false
          files: ./pyre2*.whl
